### ISSUE TITLE
Empty tasks

### ISSUE THREAD

**Issue by arshadr** [i-break-codes/scrum-board#1]
It's possible to create empty tasks by not typing anything in when creating tasks. Can't be deleted without clearing from local storage.

**Comment by i-break-codes** [comment]
Hey, nice catch. I'll release a set of bug fixes and few changes in couple of hours, thanks for raising this issue. Totally missed out on the validations part.

**Comment by i-break-codes** [comment]
Patched for now, will get some validation in the place soon. Closing for now!

Thanks :)
