### ISSUE TITLE
Cannot create task

### ISSUE THREAD

**Issue by CVarisco** [i-break-codes/scrum-board#3]
Hi,
the boar is very cool :)
I tried the demo app, but when I tried to create a task I got this error.
[![Screen Shot 2016-11-21 at 09.35.31.png](https://s18.postimg.org/geh79q8hl/Screen_Shot_2016_11_21_at_09_35_31.png)](https://postimg.org/image/pm9fqffjp/)

I wanted to warn you about this.

Bye!

**Comment by i-break-codes** [comment]
Hey, thanks a lot for raising this issue. I was deploying a hotfix for empty tasks, and forgot to add the compiled copy to gh-pages branch. Please refresh your app once and it should work. I'll push a set of fixes and some features by end of day.

**Comment by CVarisco** [comment]
Thanks man! 👍
