### ISSUE TITLE
Cannot edit task after creating it

### ISSUE THREAD

**Issue by i-break-codes** [i-break-codes/scrum-board#4]
Cannot edit a newly created task, it is editable only after refresh.

**Comment by nicolastarzia** [comment]
I can do this.
It's a delegate problem, on edit method.

**Comment by i-break-codes** [comment]
@nicolastarzia Already fixed it, but if you want to fix, you can go ahead and do it, I'll revert that in my code :)

**Comment by nicolastarzia** [comment]
Thanks!  👍
