### ISSUE TITLE
Possibility to edit column names – Support User Stories

### ISSUE THREAD

**Issue by fbnlsr** [i-break-codes/scrum-board#5]
On our physical scrum board, we have User Stories in our far-left column.

I'd like to edit the column names in order to change "Rejected" to "User Stories".

Also, it could be nice if tasks could be draggable/droppable vertically. That'd help visually align them with the User Stories they're assigned to.

**Comment by i-break-codes** [comment]
Sorry for the late reply, was damn busy. Coming to your suggestion, I like it, will consider it in v2. Thank you.

**Comment by i-break-codes** [comment]
This is now done. Thanks to @nicolastarzia

**Comment by nicolastarzia** [comment]
👍
