### ISSUE TITLE
Does not respect column

### ISSUE THREAD

**Issue by zmovirzynski** [i-break-codes/scrum-board#8]
No scrollbar created when popping column size

![image](https://cloud.githubusercontent.com/assets/9589201/21565189/085d369a-ce7c-11e6-9448-48f41b00c195.png)

**Comment by zmovirzynski** [comment]
ADD in \app\assets\stylesheetsapp.css

#production, #rejected, #pending, #development, #testing{
  overflow:auto;
}

Thanks.

**Comment by i-break-codes** [comment]
Hey thanks for the report, I'll fix it by tomorrow :)

**Comment by i-break-codes** [comment]
Just add `overflow: auto;` will not fix that issue. Need to disable `scroll` on drag, and also need to clone that element. Will fix it.

**Comment by zmovirzynski** [comment]
Thanks!

**Comment by i-break-codes** [comment]
[This is now fixed](https://github.com/i-break-codes/scrum-board/pull/9). Thanks.
